# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c70ea4a2e5eded4f65690c3e18ab48d"
name = "issue-tracker-option"
handle = "issue-tracker-option"
application_url = "https://yourself-supplement-room-racing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "diostaging.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://yourself-supplement-room-racing.trycloudflare.com/auth/callback",
  "https://yourself-supplement-room-racing.trycloudflare.com/auth/shopify/callback",
  "https://yourself-supplement-room-racing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
